server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/exam_management_system
    username: root
    password: Quang204
    driver-class-name: com.mysql.cj.jdbc.Driver

#  jpa:
#    hibernate:
#      ddl-auto: update
#    show-sql: true
#    open-in-view: false
#    properties:
#      hibernate:
#        format_sql: true
#        dialect: org.hibernate.dialect.MySQLDialect

  mail:
    host: smtp.gmail.com
    port: 587
    username: Trungquangle04@gmail.com
    password: ckkpxigkddtkavuz
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000

jwt:
  secret: my-super-secret-key-my-super-secret-key
  expiration: 18000000

##debug
#logging:
#  level:
#    org.springframework.web: DEBUG
#    org.springframework.security: DEBUG
#    org.hibernate.SQL: DEBUG

# Cấu hình AI Gemini
gemini:
  api:
    url: "https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash-lite:generateContent"
    key: "AQ.Ab8RN6KsWBr1gS-lHb_YIuCwnvvI8buoKnIv7YeJFE2xiY_OwQ"
